// Command genmain generates a wrapper main.go from an upstream main.go.
//
// The wrapper binaries (step-ca, step-kms-plugin) must differ from upstream by
// nothing except the blank import that registers the "kmip" KMS driver. Rather
// than keeping a hand-edited copy of upstream's main.go that silently drifts,
// this tool derives the wrapper from the exact upstream version pinned in the
// wrapper's go.mod and inserts that single import. CI runs it with -check, so a
// version bump that is not regenerated (or a hand edit) fails the build.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

const driverComment = "// KMIP KMS driver (step-ca-kmip)."

func main() {
	if err := run(os.Args[1:], os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, "genmain:", err)
		os.Exit(1)
	}
}

func run(args []string, stdout io.Writer) error {
	fs := flag.NewFlagSet("genmain", flag.ContinueOnError)
	wrapper := fs.String("wrapper", "", "wrapper module directory (its go.mod pins the upstream module)")
	module := fs.String("module", "", "upstream module path, e.g. github.com/smallstep/certificates")
	src := fs.String("src", "", "path of upstream main.go inside the module, e.g. cmd/step-ca/main.go")
	anchor := fs.String("anchor", "", "import path after which the driver import is inserted")
	imp := fs.String("import", "", "import path of the driver to add")
	check := fs.Bool("check", false, "do not write; fail if the existing main.go is not up to date")
	if err := fs.Parse(args); err != nil {
		return err
	}
	for name, v := range map[string]string{"wrapper": *wrapper, "module": *module, "src": *src, "anchor": *anchor, "import": *imp} {
		if v == "" {
			return fmt.Errorf("-%s is required", name)
		}
	}

	dir, version, err := upstreamModule(*wrapper, *module)
	if err != nil {
		return err
	}
	upstream, err := os.ReadFile(filepath.Join(dir, *src))
	if err != nil {
		return fmt.Errorf("reading upstream %s@%s/%s: %w", *module, version, *src, err)
	}
	generated, err := transform(upstream, fmt.Sprintf("%s@%s/%s", *module, version, *src), *anchor, *imp)
	if err != nil {
		return err
	}

	target := filepath.Join(*wrapper, "main.go")
	if *check {
		current, err := os.ReadFile(target)
		if err != nil {
			return fmt.Errorf("reading %s: %w", target, err)
		}
		if !bytes.Equal(current, generated) {
			return fmt.Errorf("%s is not up to date with %s@%s; run `make generate`", target, *module, version)
		}
		fmt.Fprintf(stdout, "%s is up to date with %s@%s\n", target, *module, version)
		return nil
	}
	if err := os.WriteFile(target, generated, 0o644); err != nil {
		return err
	}
	fmt.Fprintf(stdout, "wrote %s from %s@%s\n", target, *module, version)
	return nil
}

// upstreamModule returns the module cache directory and version of module as
// resolved by the wrapper module's build list. The module is downloaded first:
// on a clean machine (CI) `go list -m` reports an empty Dir for modules that are
// not in the module cache yet.
func upstreamModule(wrapperDir, module string) (dir, version string, err error) {
	if _, err := goCommand(wrapperDir, "mod", "download", module); err != nil {
		return "", "", err
	}
	out, err := goCommand(wrapperDir, "list", "-m", "-f", "{{.Dir}}\t{{.Version}}", module)
	if err != nil {
		return "", "", err
	}
	dir, version, ok := strings.Cut(strings.TrimSpace(string(out)), "\t")
	if !ok || dir == "" || version == "" {
		return "", "", fmt.Errorf("go list -m %s: unexpected output %q", module, out)
	}
	return dir, version, nil
}

func goCommand(dir string, args ...string) ([]byte, error) {
	cmd := exec.Command("go", args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) {
			return nil, fmt.Errorf("go %s: %w: %s", strings.Join(args, " "), err, ee.Stderr)
		}
		return nil, fmt.Errorf("go %s: %w", strings.Join(args, " "), err)
	}
	return out, nil
}

// transform returns upstream with a "generated" header and one extra blank
// import placed right after the anchor import. It is purely additive: removing
// the header and the inserted lines yields upstream byte for byte (tested).
func transform(upstream []byte, origin, anchor, imp string) ([]byte, error) {
	re := regexp.MustCompile(`(?m)^[ \t]*_[ \t]+"` + regexp.QuoteMeta(anchor) + `"[ \t]*\n`)
	matches := re.FindAllIndex(upstream, -1)
	switch len(matches) {
	case 0:
		return nil, fmt.Errorf("anchor import %q not found in %s", anchor, origin)
	case 1:
	default:
		return nil, fmt.Errorf("anchor import %q found %d times in %s", anchor, len(matches), origin)
	}
	end := matches[0][1]

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by internal/genmain from %s; DO NOT EDIT.\n\n", origin)
	b.Write(upstream[:end])
	fmt.Fprintf(&b, "\n\t%s\n\t_ %q\n", driverComment, imp)
	b.Write(upstream[end:])

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("generated source does not parse: %w", err)
	}
	return out, nil
}
