package main

import (
	"fmt"
	"strings"
	"testing"
)

const upstream = `package main

import (
	"fmt"

	// Enabled kms interfaces.
	_ "go.step.sm/crypto/kms/pkcs11"
	_ "go.step.sm/crypto/kms/yubikey"

	// Enabled cas interfaces.
	_ "github.com/smallstep/certificates/cas/softcas"
)

func main() { fmt.Println("hi") }
`

const (
	origin = "example.com/up@v1.2.3/cmd/x/main.go"
	anchor = "go.step.sm/crypto/kms/yubikey"
	imp    = "example.com/driver/kms/kmip"
)

func TestTransformInsertsOneImportAfterAnchor(t *testing.T) {
	got, err := transform([]byte(upstream), origin, anchor, imp)
	if err != nil {
		t.Fatal(err)
	}
	s := string(got)
	if n := strings.Count(s, `_ "`+imp+`"`); n != 1 {
		t.Fatalf("driver import appears %d times, want 1:\n%s", n, s)
	}
	if strings.Index(s, `"`+anchor+`"`) > strings.Index(s, `"`+imp+`"`) {
		t.Fatalf("driver import is not after the anchor:\n%s", s)
	}
	if !strings.HasPrefix(s, "// Code generated by internal/genmain from "+origin+"; DO NOT EDIT.\n") {
		t.Fatalf("missing generated header:\n%s", s)
	}
}

// The wrapper must differ from upstream only by additions: dropping the header
// and the inserted lines must give upstream back byte for byte.
func TestTransformIsPurelyAdditive(t *testing.T) {
	got, err := transform([]byte(upstream), origin, anchor, imp)
	if err != nil {
		t.Fatal(err)
	}
	header := fmt.Sprintf("// Code generated by internal/genmain from %s; DO NOT EDIT.\n\n", origin)
	inserted := fmt.Sprintf("\n\t%s\n\t_ %q\n", driverComment, imp)
	back := strings.Replace(strings.TrimPrefix(string(got), header), inserted, "", 1)
	if back != upstream {
		t.Fatalf("removing the additions does not restore upstream.\nwant:\n%s\ngot:\n%s", upstream, back)
	}
}

func TestTransformRejectsMissingOrAmbiguousAnchor(t *testing.T) {
	if _, err := transform([]byte(upstream), origin, "no/such/import", imp); err == nil {
		t.Fatal("expected an error for a missing anchor")
	}
	dup := strings.Replace(upstream, "\t_ \"go.step.sm/crypto/kms/pkcs11\"\n", "\t_ \"go.step.sm/crypto/kms/yubikey\"\n", 1)
	if _, err := transform([]byte(dup), origin, anchor, imp); err == nil {
		t.Fatal("expected an error for a duplicated anchor")
	}
}
